language: rust
sudo: true
rust:
    - stable

cache: cargo

before_script:
    - which python3
    - python3 -V
    - sudo apt-get install python3-pip
    - pip3 install Flask
    - cd integration && python3 server.py&
    - sleep 2
    - export VERSION=$(grep '^version' Cargo.toml | cut -f2 -d'"')

deploy:
  provider: script
  script:
    - echo "VERSON=$VERSION"
    - ci/check_tag
    - ci/create_tarballs
    - ci/upload.sh "$VERSION" "target/tarballs/hurl-$VERSION-x86_64-linux.tar.gz"
  skip_cleanup: true
  on:
    all_branch: true
  # tags: true

