language: rust
sudo: true
rust:
    - stable

cache: cargo

before_script:
    - which python3
    - python3 -V
    - sudo apt-get install python3-pip
    - pip3 install Flask
    - cd integration && python3 server.py&
    - sleep 2
    - export VERSION=$(grep '^version' Cargo.toml | cut -f2 -d'"')

deploy:
    - echo "$VERSION"
    - ci/create_tarballs
    - ci/upload.sh "$VERSION" "target/tarballs/hurl-$VERSION-x86_64-linux.tar.gz"


