language: rust
sudo: true
rust:
    - stable

cache: cargo

before_script:
    - which python3
    - python3 -V
    - sudo apt-get install python3-pip
    - pip3 install Flask
    - cd integration && python3 server.py&
    - sleep 2
    - export VERSION=$(grep '^version' Cargo.toml | cut -f2 -d'"')

script:
    - cargo build i--release --verbose
    - cargo test --verbose
    - export PATH="$PWD/target/release:$PATH"
    - integration/integration.sh


deploy:
  provider: script
  script: ci/deploy.sh
  skip_cleanup: true
  on:
    all_branch: true
  # tags: true

