language: rust
sudo: true
rust:
    - stable

#cache: cargo

before_script:
    - which python3
    - python3 -V
    - sudo apt-get install python3-pip
    - pip3 install Flask
    - cd integration && python3 server.py&
    - sleep 2


